[project]
name = "feature-viz"
version = "0.1.0"
description = "feature map visualisation (prototype)"
authors = [
    {name = "Florian Förster",email = "florian.foerster@mb.tu-chemnitz.de"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
